export const EVENT_KEYS = {
  UPDATE_PLAYER_STAT: 'update-player-stat',
  UPDATE_PLAYER_IN_TEAM: 'update-player-in-team',
  ADD_PLAYER_TO_TEAM: 'add-player-to-team',
  REMOVE_PLAYER_IN_TEAM: 'remove-player-in-team',
  SUBSTITUTE_PLAYER: 'substitute-player',
  UPDATE_COACH_STAT: 'update-coach-stat',
  ADD_COACH_TO_TEAM: 'add-coach-to-team',
  REMOVE_COACH_IN_TEAM: 'remove-coach-in-team',
  UPDATE_OFFICIAL_IN_GAME: 'update-official-in-game',
  ADD_OFFICIAL_TO_GAME: 'add-official-to-game',
  REMOVE_OFFICIAL_IN_GAME: 'remove-official-in-game',
  UPDATE_TEAM_STAT: 'update-team-stat',
  START_GAME_LIVE_MODE: 'start-game-live-mode',
  END_GAME_LIVE_MODE: 'end-game-live-mode',
  END_GAME: 'end-game',
  END_PERIOD: 'end-period',
  UPDATE_CLOCK_STATE: 'update-clock-state',
  UPDATE_CLOCK_TIME_AND_PERIOD: 'update-clock-time-and-period',
};
